import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { NavMenu } from "@/components/NavMenu";
import { ModeToggle } from "@/components/DarkModeToggle";
import { getServerSession } from "next-auth/next";
import { options } from "@/app/api/auth/[...nextauth]/options";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  console.log(session);
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex items-center justify-between px-4 py-4">
            <NavMenu />
            <div className="flex direction-row gap-4">
              <ModeToggle />
              <Avatar>
                <AvatarImage src={session?.user.image || ""} alt="@shadcn" />
                <AvatarFallback>
                  {session?.user.name?.[0] || "U"}
                </AvatarFallback>
              </Avatar>
            </div>
          </div>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
